name: List Pull Requests

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  list-prs:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run PR Tool
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python main.py

      - name: Upload Reports
        uses: actions/upload-artifact@v5
        with:
          name: pr-reports
          path: |
            pr_report.json
            pr_report.xlsx
